### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by someghuser** [kagenihisomi/sd-webui-gallery#1]
webui-docker-auto-cpu-1  | *** Error loading script: gallery.py
webui-docker-auto-cpu-1  |     Traceback (most recent call last):
webui-docker-auto-cpu-1  |       File "/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
webui-docker-auto-cpu-1  |         script_module = script_loading.load_module(scriptfile.path)
webui-docker-auto-cpu-1  |       File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
webui-docker-auto-cpu-1  |         module_spec.loader.exec_module(module)
webui-docker-auto-cpu-1  |       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
webui-docker-auto-cpu-1  |       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
webui-docker-auto-cpu-1  |       File "/stable-diffusion-webui/extensions/sd-webui-gallery/scripts/gallery.py", line 8, in <module>
webui-docker-auto-cpu-1  |         from scripts.utils import (
webui-docker-auto-cpu-1  |     ImportError: cannot import name 'MAX_DISPLAY' from 'scripts.utils' (/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py)
webui-docker-auto-cpu-1  | 
webui-docker-auto-cpu-1  | ---

**Comment by kagenihisomi** [comment]
How did you get that error?
